[package]
name = "rlsf-verified-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
vstd = { git = "https://github.com/verus-lang/verus.git" }
rlsf-verified = { path = "..", features = ["std"] }

[profile.release]
lto = false
codegen-units = 1
debug = true
